### ISSUE TITLE
web-extension port

### ISSUE THREAD

**Issue by paracetamolo** [chatziko/location-guard#30] opened 2017-10-25 07:13 UTC
This is a bug tracking the progress of the web-extension port, code is on the webextension branch.

- ~~chrome: check if removing `persistent:false` from manifest causes problems~~
- ff all: options and demo page are not displayed after installation
- ff all: migrate user preferences from old api
- ff desktop: pop-up blinks when choosing noise level
- ff android: not working
- ms edge: needs testing

**Comment by dfwdraco76** [comment] 2017-10-26 22:01
I came looking for an update about the Firefox extension and webextension compatibility.  Does this mean there will be one...?

**Comment by paracetamolo** [comment] 2017-10-31 11:37
`persistent:false` is useful in Chrome and it seems not supported in FF. Moreover FF needs the tabs permission declared in the manifest. I'm maintaining two manifest.json files for now.

**Comment by chatziko** [comment] 2017-11-01 18:39
Anybody who has time, please test the xpi in this zip: [location-guard-embeded-1.3.zip](https://github.com/chatziko/location-guard/files/1435261/location-guard-embeded-1.3.zip)

This is an **embedded** addon that works on **FF 56** (not on FF 57, I'll create another xpi for this), and allows to migrate the settings from the legacy addon. So please:
* install the old addon from https://addons.mozilla.org/en-US/firefox/addon/location-guard/
* modify some of the settings
* install the xpi as follows:
  * set xpinstall.signatures.required = false in about:config
  * drag the xpi to a firefox window, or download and open it in firefox for Android.
* check that the settings are still there
* test as much of the functionality of the addon as possible.

The above for both the desktop and the android version.

If you see anything strange please:
* save all contents of the browser console (control-shift-J) to a file
* reply to this message with detailed steps to reproduce the issue, and attach the browser console file.

Thanks in advance!

**Comment by ExE-Boss** [comment] 2017-11-01 18:45
Actually, the `xpinstall.signatures.required` setting no longer exists in Beta or Stable since Firefox 48, you instead need to temporarily install the extension through `about:debugging`.

**Comment by chatziko** [comment] 2017-11-01 19:48
There's a small issue with upgrading an _existing_ addon with a temporary one installed via ```about:debugging```: pressing "Remove" completely uninstalls the temporary addon, together with all its saved data. Then the old addon is re-installed, but with default settings.

But I realize now that an alternative way to go back to the old version is to simply restart the browser. This removes the temporary addon without affecting the old one. Quite handy...

Btw the old method still works fine on my machine (FF 56).

**Comment by chatziko** [comment] 2017-11-10 15:28
The port is ready and uploaded to addons.mozilla.org.
* On Firefox 56 users will upgrade to version [2.0.2](https://addons.mozilla.org/en-US/firefox/addon/location-guard/versions/?page=1#version-2.0.2) which is a webextensions addon with a tiny legacy wrapper that migrates the settings.
* Once a user upgrades to Firefox 57 he will automatically get version [2.1.0](https://addons.mozilla.org/en-US/firefox/addon/location-guard/versions/?page=1#version-2.1.0) which is webextensions-only.

So I'm closing this. Please open a new issue if you spot any problem.

**Closed by chatziko** 2017-11-10 15:28 UTC
