### ISSUE TITLE
I can't use Location Guard on Brave

### ISSUE THREAD

**Issue by jades1112** [chatziko/location-guard#87] opened 2022-03-16 14:17 UTC
### Please read the FAQ before opening an issue

https://github.com/chatziko/location-guard#why-some-websites-detect-my-location-although-i-use-location-guard

In particular, note that Location Guard protects against JavaScript-based and not IP-based geolocation.

### Test Location Guard on browserleaks.com

Please report whether your issue appears on
https://browserleaks.com/geo

If the issue does not appear on browserleaks.com, but appears on some other website, that website is likely using IP-based or some other form of geolocation. Location Guard is not supposed to protect against other types of geolocation.

### Include concrete steps to reproduce the issue

This is the __most important__ information for fixing the problem:

1. Go to ...
2. Click on ...
3. Scroll down to ...
4. See error ...

### Please complete the following information

 - OS: [e.g. Windows]
 - Browser [e.g. Chrome, Firefox]
 - Version [e.g. 77]

**Comment by jades1112** [comment] 2022-03-16 14:38
IT worked just fine , i am having this problem since 4 days

**Comment by chatziko** [comment] 2022-03-16 19:32
If you don't mention anything about the problem you are experiencing, how are we supposed to help?
There is a template for reporting issues exactly for this reason.

Did you try the latest version v2.4.2?
There was an issue with tiles loaded via http (instead of https) a few days ago, which is solved in the latest version. I've never used Brave so I have no idea what it does, but check which version of the addon is used.

**Comment by jades1112** [comment] 2022-03-16 19:35
Yes its 2.4.2 version , i attached how it appears. It worked before . 4
days now that it’s not working. It didnt work on google chrome but its
fixed today. Not the same for brave . You can try it in brave and see .

**Comment by jades1112** [comment] 2022-03-17 07:49
![Capture](https://user-images.githubusercontent.com/101726163/158761532-7ef9d126-90ae-460e-bc73-4e9b1189a33f.PNG)
Here check how it appears, it doesnt load the map.

**Comment by jades1112** [comment] 2022-03-17 07:50
Keeps staying like this , now for 5 days , can you please check?>

**Comment by chatziko** [comment] 2022-03-17 09:34
I tried it. It seems that openstreetmap does not want to serve map tiles to Brave. Try to open:

https://b.tile.openstreetmap.org/2/3/1.png

It works on all browsers, but fails on Brave.

It seems the problem is that Brave does not send the `sec-ch-ua` header. Here's the exact request that Brave sends, which fails:
```
curl 'https://a.tile.openstreetmap.org/2/2/1.png' \
  -H 'authority: a.tile.openstreetmap.org' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36' \
  -H 'accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'sec-gpc: 1' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: image' \
  -H 'accept-language: en-US,en;q=0.9' \
  --compressed
```

If you just add
```
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"' \
```
then it succeeds!

Anyway, this is a problem with Brave/openstreetmap, not with Location Guard. There's nothing I can do about it.

**Comment by jades1112** [comment] 2022-03-17 09:56
But it worked just fine 4 days ago , and i was using for more then a year .
What can i do now ? How can i fix it?

**Comment by chatziko** [comment] 2022-03-17 11:12
I uploaded a workaround (use the german openstretmap server no Brave). Wait until v2.4.3 appears online (it's under review now) and give it a try.

**Comment by jades1112** [comment] 2022-03-17 11:21
Ok and you think it will be fixed on brave after the update its done ?
Thank you sir , appreciate everything.

**Comment by chatziko** [comment] 2022-03-18 12:22
Seems to work fine, so I'm closing this (feel free to reopen if the issue persists).

**Closed by chatziko** 2022-03-18 12:22 UTC
