### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by IronOlmi** [chatziko/location-guard#6] opened 2015-02-15 00:10 UTC
My review in addons.mozilla:
"Doesn't work (using FF 35.0.1). Icon doesn't appear in toolbar in any sites. Options page doesn't work. Demopage works only after pressing F5 multiple times. I really like the idea of this addon and I would really use it if it works." 

More specfic information about this problem: Addon doesn't do anything. Icon doesn't appear on toolbar in any sites. Graphics doesn't work in options, privacy levels and fixed location page. And I can't change any settins in those page. FAQ  page doesn't work at all. Demo page works after hitting F5 many times. 
![demo](https://cloud.githubusercontent.com/assets/11011114/6201512/70ed6c60-b4b7-11e4-8a08-baf0cb7b47d7.png)
![fixedpos](https://cloud.githubusercontent.com/assets/11011114/6201513/70f75932-b4b7-11e4-8a6f-4cc4a758f3bd.png)
![options](https://cloud.githubusercontent.com/assets/11011114/6201514/70fc3df8-b4b7-11e4-8df4-5c029bf13a16.png)
![privacylevels](https://cloud.githubusercontent.com/assets/11011114/6201515/71018c7c-b4b7-11e4-9ced-87fff4d678d3.png)

I'm using Lubuntu 14.10 64bit on laptop. 

I only had these addons enabled when I tested Location Guard: Adblock Edge, Ghostery, Flash Control, HTTPS Everywhere. I tested Location Guard again without any other addons on clean OS install (reason why I use linux, its fast to reinstall) and it didn't help at all. 

I'll test Location Guard in Windows 7 (with same other addons) later today and inform what happens. 

And my apologies about my bad english.

**Comment by chatziko** [comment] 2015-02-16 13:37
Hello and thanks a lot for helping to solve this issue!

The problem seems weird, I also run ubuntu and it never happened to me. Moreover, I just tried Lubuntu 14.10 on a virtualbox machine, and it worked fine.

Can you maybe reproduce this issue in a clean virtualbox machine? If so, can you share the machine with me so that I can reproduce it from here?

**Comment by chatziko** [comment] 2015-04-08 10:43
Hello again,

we just released a new version 1.2.0 of Location Guard in which much of the Firefox code has been rewritten.

It's likely that this version fixes your problem, could you please upgrade to 1.2.0 and give it a try?
https://addons.mozilla.org/en-US/firefox/addon/location-guard/

Thanks a lot in advance for your help!

**Comment by mahdiG** [comment] 2015-06-10 09:00
Hello. I'm using Location Guard 1.2.0.1 on firefox 38.0.5 on Debian Stretch; The icon doesn't appear and privacy levels/fixed location don't work. But for me the option page is graphically correct.

**Comment by chatziko** [comment] 2015-06-10 09:16
Hi and thanks for the report!

The problem with this bug is that I've been unable to reproduce it no matter what I try.
Could you maybe reproduce it in a virtualbox machine (with debian would be fine) and send me the whole machine?

**Comment by chatziko** [comment] 2016-03-31 19:27
This issue is older than a year, concerns an old version of the addon and could not be reproduced.

I'm closing it for now. Feel free to re-open if you can reproduce it with the latest version.

**Closed by chatziko** 2016-03-31 19:27 UTC
Labels: bug
